### ISSUE TITLE
[Week 5] Twitter - Submission

### ISSUE THREAD

**Issue by DGh0st** [DGh0st/Tweety#2]
My twitter application for week 5 is complete, please review. /cc @codepathreview

**Comment by avo1** [comment]
:+1: Wow, great work! We added this homework so that you'll have the experience building an app that's more similar in complexity to a production app. The optional account switching feature is interesting because you have to think about how TwitterClient is caching the access token to make sure it works correctly for multiple accounts.

We have a detailed [Project 5 Feedback Guide](http://courses.codepath.com/snippets/ios_university/feedback_guides/project_5_feedback.md) which covers the best practices for implementing this assignment. Read through the feedback guide point-by-point to determine ways you might be able to improve your submission. You should consider going back and implementing these improvements as well.

If you have any particular questions about the assignment or the feedback, feel free to reply here or email us at universitysupport@codepath.com.
